# blocklist
branches:
  except:
 

# safelist
branches:
  only:
  - master

language: node_js
node_js:
  - "12"
script:
 - echo "Deploy!!"
install:
  - npm install -g firebase-tools
after_success:
  - firebase deploy --project show-kase --token $FIREBASE_TOKEN
